#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v10
# autospec commit: 5905be9
#
Name     : R-fUnitRoots
Version  : 4040.81
Release  : 45
URL      : https://cran.r-project.org/src/contrib/fUnitRoots_4040.81.tar.gz
Source0  : https://cran.r-project.org/src/contrib/fUnitRoots_4040.81.tar.gz
Summary  : Rmetrics - Modelling Trends and Unit Roots
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-fUnitRoots-lib = %{version}-%{release}
Requires: R-fBasics
Requires: R-timeSeries
Requires: R-urca
BuildRequires : R-fBasics
BuildRequires : R-timeSeries
BuildRequires : R-urca
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package lib
Summary: lib components for the R-fUnitRoots package.
Group: Libraries

%description lib
lib components for the R-fUnitRoots package.


%prep
%setup -q -n fUnitRoots
pushd ..
cp -a fUnitRoots buildavx2
popd
pushd ..
cp -a fUnitRoots buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1715787501

%install
export SOURCE_DATE_EPOCH=1715787501
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/fUnitRoots/DESCRIPTION
/usr/lib64/R/library/fUnitRoots/INDEX
/usr/lib64/R/library/fUnitRoots/Meta/Rd.rds
/usr/lib64/R/library/fUnitRoots/Meta/features.rds
/usr/lib64/R/library/fUnitRoots/Meta/hsearch.rds
/usr/lib64/R/library/fUnitRoots/Meta/links.rds
/usr/lib64/R/library/fUnitRoots/Meta/nsInfo.rds
/usr/lib64/R/library/fUnitRoots/Meta/package.rds
/usr/lib64/R/library/fUnitRoots/NAMESPACE
/usr/lib64/R/library/fUnitRoots/NEWS.md
/usr/lib64/R/library/fUnitRoots/R/fUnitRoots
/usr/lib64/R/library/fUnitRoots/R/fUnitRoots.rdb
/usr/lib64/R/library/fUnitRoots/R/fUnitRoots.rdx
/usr/lib64/R/library/fUnitRoots/help/AnIndex
/usr/lib64/R/library/fUnitRoots/help/aliases.rds
/usr/lib64/R/library/fUnitRoots/help/fUnitRoots.rdb
/usr/lib64/R/library/fUnitRoots/help/fUnitRoots.rdx
/usr/lib64/R/library/fUnitRoots/help/paths.rds
/usr/lib64/R/library/fUnitRoots/html/00Index.html
/usr/lib64/R/library/fUnitRoots/html/R.css
/usr/lib64/R/library/fUnitRoots/unitTests/Makefile
/usr/lib64/R/library/fUnitRoots/unitTests/runTests.R
/usr/lib64/R/library/fUnitRoots/unitTests/runit.DickeyFullerPValues.R
/usr/lib64/R/library/fUnitRoots/unitTests/runit.MacKinnonPValues.R
/usr/lib64/R/library/fUnitRoots/unitTests/runit.UnitRootUrcaInterface.R
/usr/lib64/R/library/fUnitRoots/unitTests/runit.UnitrootTests.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/fUnitRoots/libs/fUnitRoots.so
/V4/usr/lib64/R/library/fUnitRoots/libs/fUnitRoots.so
/usr/lib64/R/library/fUnitRoots/libs/fUnitRoots.so
